namespacelabs/foundation

internal/frontend/cuefrontend/resources.go
internal/parsing/resourceinstance.go
library/oss/minio/prepare/main.go

Providers should do field level validation.

Parsing: don't require "intent" in resources.

---

README.md
examples/README.md

Small fix to have correct links to examples repository

fix links to examples

---

internal/frontend/cuefrontendopaque/tests.go
internal/parsing/env.go
internal/parsing/integration/api/util.go
internal/planning/startup/compute.go
internal/runtime/kubernetes/deployment.go
internal/support/env.go
internal/testdata/integrations/dockerfile/complex/server.cue
internal/testdata/integrations/dockerfile/complex/test/test.sh
internal/testing/fixture.go

Enable env and arg to be set on tests.

---

internal/cli/cmd/deployplan.go

Testing:
1. Complied a deployment plan and published to local registry:
```
nsdev deploy server --upload_plan_to=us-docker.pkg.dev/foundation-344819/giulio-argo-test --upload_to_registry
```
2. Applied the plan image to local cluster with insecure flag:
```
nsdev deploy-plan k3d-ns-registry.nslocal.host:61367/us-docker.pkg.dev/foundation-344819/giulio-argo-test@sha256:d56294101a531b8bea2e740f06fc7fef45da937c7ef2db753ecea463d2c53205 --image --insecure
```

feat: cmd/deployplan: insecure flag

---

internal/planning/deploy/deploy.go
internal/planning/deploy/resources.go
internal/planning/deploy/runtimeconfig.go
internal/planning/stack.go
internal/testing/prepare.go

feat: filling "service.ingress" field in the runtime config.

---

internal/cli/cmd/cmd.go
internal/cli/cmd/describe.go
internal/cli/cmd/ls.go
internal/cli/fncobra/locbound.go
internal/parsing/resourceprovider.go

* `ls -l` to list objects in packages
* `describe` to print deatils about objects.

Add introspection commands for ns objects.

---

internal/build/buildkit/daemon.go
internal/runtime/docker/client.go

RemoveBuildkitd should remove related volumes as well.

---

internal/auth/auth.go
internal/auth/autherror.go
internal/auth/userauth.go
internal/clerk/clerk.go
internal/cli/cmd/doctor.go
internal/cli/cmd/login.go
internal/fnapi/fnapi.go
internal/fnapi/map.go
internal/fnapi/naming.go
internal/fnapi/signin.go
internal/github/jwt.go
internal/providers/nscloud/api/ssh.go
internal/providers/nscloud/registry.go
orchestration/client.go
orchestration/service/wire.go

Also in this `GenerateToken` method was changed to package level
function with options to decided which auth method to use when generate
access token.

auth: move UserAuth management and token generation into auth pkg

---

internal/auth/auth.go

internal/auth: set audience on Github JWT

---

internal/cli/cmd/cluster/cmd.go
internal/providers/nscloud/wait.go

nscloud: Implement flag to wait for kube system resources.

---

go.mod
go.sum
internal/auth/tokens.go
internal/providers/nscloud/api/rpc.go

provider/nscloud: exchange user tokens to tenant tokens for cluster ops

---

.github/workflows/e2e.yaml
.github/workflows/scripts/dev.sh

e2e test for ns dev

---

internal/auth/auth.go
internal/clerk/clerk.go

Fixes NSL-645
Contributes NSL-659

clerk: prefix  clerk tokens with `ct_` for prod and `devct_` for dev

---

.github/workflows/e2e.yaml
internal/cli/fncobra/main.go
internal/cli/fncobra/ns/main.go
std/tasks/simplelog/logger.go

Log actions to a file and capture the artifact.

---

internal/cli/cmd/auth/login.go
internal/fnapi/signin.go

This allows to upgrade authentication methods.

Pass supported_kinds to StartLogin.

---

internal/cli/cmd/auth/githubtoken.go
internal/fnapi/tenants.go

nsc: print workspace name if any when exchanging github tokens.

---

internal/auth/tokens.go
internal/cli/cmd/auth/login.go
internal/fnapi/signin.go
internal/fnapi/tenants.go

Introduce workspace flag to separate auth tokens per workspace

---

go.mod
internal/artifacts/registry/static.go
internal/cli/cmd/cluster/build.go
internal/cli/cmd/cluster/proxy.go

cmd/cluster/build: add support for multi-arch build using buildkit

---

internal/cli/cmd/cluster/run.go
internal/providers/nscloud/api/rpc.go
internal/providers/nscloud/api/types.go
internal/providers/nscloud/ctl/wait.go

Implement container waiting by polling the cluster summary.

---

.envrc

If nix and direnv are installed then contributing to the project becomes dramatically easier.
Just `cd foundation` and that's it.
Related:
* https://direnv.net/#basic-installation
* https://github.com/direnv/direnv/wiki/Nix

devenv: automatically cfg devenv via direnv/nix

---

internal/artifacts/oci/reference.go
internal/artifacts/oci/remote.go

artifacts/oci: add option to use mirror for docker hub

---

internal/cli/cmd/cluster/buildkit.go
internal/cli/cmd/cluster/buildproxy.go
internal/cli/cmd/cluster/buildx.go
internal/cli/cmd/cluster/grpcproxy.go

Buildkit grpc proxy

---

internal/cli/cmd/cluster/buildkit.go
internal/cli/cmd/cluster/buildproxy.go
internal/cli/cmd/cluster/buildx.go
internal/cli/cmd/cluster/grpcproxy.go

worker info JSON file looks like:
```
{
"record": [
{
"ID": "namespace-amd64-builder",
"Labels": {
"org.mobyproject.buildkit.worker.executor": "oci",
"org.mobyproject.buildkit.worker.hostname": "namespace-amd64-builder",
"org.mobyproject.buildkit.worker.network": "cni",
"org.mobyproject.buildkit.worker.oci.process-mode": "sandbox",
"org.mobyproject.buildkit.worker.selinux.enabled": "false",
"org.mobyproject.buildkit.worker.snapshotter": "overlayfs"
},
"platforms": [
{ "Architecture": "amd64", "OS": "linux" },
{ "Architecture": "amd64", "OS": "linux", "Variant": "v2" },
{ "Architecture": "amd64", "OS": "linux", "Variant": "v3" },
{ "Architecture": "amd64", "OS": "linux", "Variant": "v4" },
{ "Architecture": "386", "OS": "linux" }
],
"GCPolicy": [
{ "keepDuration": 604800000000000, …
```

cmd/cluster: hidden flag injects ListWorkers response in grpc proxy

---

go.mod
universe/db/postgres/db.go
universe/db/postgres/row.go
universe/db/postgres/rows.go
universe/db/postgres/span.go

ensure we report SQL errors on db.Query

---

internal/providers/onepassword/secrets.go

1Password: provide better error if no account is configured

---

internal/cli/cmd/aws/cmd.go
internal/cli/cmd/aws/ecr.go

Add experimental command `nsc aws ecr-docker-login`

---

universe/vault/credentials.go

The Vault client currently does not support automatic token renewal. This is a simple approach that keeps renewing the token until the original context is cancelled.
Some things to consider:
- Add retry. With backoff.
- Tokens have a max-TTL, give up once we reach it.
- The renew request might return a different auth context, with a different lease duration. This could happen if e.g. the max-TTL is 1.5h, and the initial token was for 1h.
- Have some way to tell the consumer that the client token has expired, and there's no way to renew it. In this case, the client should attempt to reconnect.
- The Secret ID may or may not allow issuing more than one token.
- If it allows, reconnect with the same secret ID. If not, then reconnecting will fail immediately.

vault: renew tokens

---

std/go/grpc/servercore/listener.go

Adds the `-grpcserver_multiplex_tls` flag. When set to one of the named listeners, the default listener will multiplex TLS connections onto this named listener. (The named listener will still be started on a separate port as well.)

grpc: add -grpcserver_multiplex_tls flag

---

std/grpc/wire.go

So it possible to configure custom credentials, etc.

grpc: add an option to provide gRPC dial opts in Loopback func

---

internal/cli/cmd/auth/checkauth.go
internal/fnapi/fnapi.go
internal/fnapi/tokens.go

The intention is to check whether the token has been revoked.

auth: do an online check for session tokens

---

internal/cli/cmd/auth/checklogin.go
internal/cli/cmd/auth/cmd.go

auth: add hidden check-login --duration command

---

cmd/nsc/cmd/register.go
internal/cli/cmd/cluster/bazel.go
internal/providers/nscloud/api/rpc.go
internal/providers/nscloud/api/types.go

add initial command to set up bazel remote cache config

---

internal/cli/cmd/cluster/git.go
internal/cli/cmd/cluster/gitcheckout.go

Also fix https git repo parsing
Part of: NSL-3898

cmd/gitcheckout: run git config with repo path

---

internal/cli/cmd/cluster/gitcheckout.go

Only process .gitmodules entries if they point to a "commit" type object.
Do this because regular git submodule commands behave like that.
Bug: NSL-3880

git-checkout: Skip stale .gitmodules entries

---

internal/cli/cmd/cluster/buildx.go
internal/cli/cmd/cluster/server_side_buildx.go
internal/fnapi/tenants.go
internal/providers/nscloud/api/rpc.go
internal/providers/nscloud/metadata/instancemd.go

buildx: support server-side proxy

---

internal/providers/vault/provider.go
universe/vault/credentials.go

universe/vault: support oidc and jwt auth methods

---

.goreleaser.yaml
cmd/bazel-credential-nsc/main.go
install/install_nsc.sh
internal/cli/cmd/cluster/bazel.go
internal/cli/cmd/cluster/bazelcredhelper.go
internal/fnerrors/errors.go
internal/providers/nscloud/api/rpc.go
internal/providers/nscloud/api/types.go

Uses Bearer token in header auth.
Bug: NSL-3913

bazel: Add credential helper

---

internal/auth/tokens.go

8h is the maximum allowed by the server.

auth: Increase short-term token limit.

---

internal/fnapi/fnapi.go

Add a more specific error on I/O timeouts.

---

go.mod
go.sum
internal/cli/cmd/cluster/server_side_buildx.go

If the server provides it, use the "full endpoint".

buildx: accept full endpoint including port

---

framework/secrets/combined/combined.go
framework/secrets/interface.go
internal/planning/secrets/secrets.go
internal/providers/onepassword/secrets.go
internal/providers/vault/approle.go
internal/providers/vault/ca.go
internal/providers/vault/certificate.go
internal/providers/vault/secret.go
internal/versions/versions.json

Do not fail Vault provider on optional secrets.

---

go.mod
go.sum

This contains a few bug fixes.

Upgrade go-grpc to v1.68.1

---

internal/cli/cmd/cluster/build.go

Add ability to attach secrets with nsc build.

---

internal/cli/cmd/cluster/run.go

Global resolution for `nsc run --on`

---

library/oss/postgres/prepare/database/main.go

Just do retries on fast failures.

Do not apply schemas in a transaction.

---

go.mod
go.sum
internal/cli/cmd/cluster/artifact.go

cmd/artifact: Add cache-url command for pull-through caching.

---

go.mod
go.sum

I manually reviewed https://github.com/golang-jwt/jwt/compare/v4.5.1...v4.5.2

go get github.com/golang-jwt/jwt/v4@v4.5.2

---

internal/cli/cmd/cluster/server_side_buildx.go

Avoids race conditions when multiple builds are started in parallel.
Also avoid writing credentials files at all if instance credentials can be reused.

buildx: atomic client cred writing

---

go.mod
go.sum
internal/build/buildkit/client.go
internal/cli/cmd/cluster/buildx.go
internal/cli/cmd/cluster/server_side_buildx.go
internal/providers/nscloud/api/rpc.go

nsc docker buildx setup: Expose ability to select a remote builder tag.

---

.github/workflows/scripts/ns_cluster_tests.sh
internal/cli/cmd/cluster/attachdocker.go
internal/cli/cmd/cluster/create.go
internal/cli/cmd/cluster/ssh.go
internal/prepare/nscloud.go
internal/providers/nscloud/api/rpc.go
internal/providers/nscloud/cluster.go

Use compute API by default.

---

internal/cli/cmd/cluster/artifact.go
internal/cli/cmd/cluster/bazel.go
internal/cli/cmd/cluster/pants.go

Make long-used commands visible.

---

internal/cli/cmd/test.go
std/tasks/flags.go
std/tasks/logging.go
std/tasks/throttle.go

Make build and test parallelism configurable.

---

internal/cli/cmd/deploy.go

to override client-side config conflicts

deploy: implement force-apply flag

---

framework/ulimit/ulimit_unix.go
framework/ulimit/ulimit_windows.go

framework/ulimit: Implement SetCoreFileLimit.

---

internal/cli/cmd/cluster/attachdocker.go
internal/cli/cmd/cluster/create.go
internal/cli/cmd/cluster/run.go
internal/cli/cmd/cluster/ssh.go
internal/cli/cmd/cluster/terminal/create.go
internal/prepare/nscloud.go
internal/providers/nscloud/api/rpc.go
internal/providers/nscloud/cluster.go

(Keep it as a no-op in create).

remove --compute_api, it's now the default.

---

internal/cli/cmd/cluster/bazel.go
internal/providers/nscloud/api/types.go

Add json output option to `nsc bazel cache setup`

---

internal/cli/cmd/cluster/bazel.go

Allow selecting where to store the emitted credentials.
Towards NSL-6006

nsc bazel cache setup:

---

internal/cli/cmd/cluster/create.go

nsc create: respect existing k3s config if any.

---

internal/cli/cmd/cluster/github/build.go

nsc: add --platform flag to nsc github build-base-image

---

internal/cli/cmd/cluster/buildx.go

Fix JSON output when there are no builders configured.

---

internal/artifacts/oci/readfiles.go

nsc: Add support for docker format images in base-image upload command

---

internal/artifacts/oci/readfiles.go
internal/cli/cmd/baseimage/upload_base_image.go

nsc: Use flattened image for digest calculation in base-image upload

---

internal/cli/cmd/ls.go
internal/networking/ingress/define_ingress.go

- **ingress: set ingressClassName instead of relying on annotations.**
- **added -k as a filter to `ns list`.**

descriptions
