namespacelabs/foundation

install/install.sh

On Linux and macOS, `mktemp` works slightly different. On Linux `-t` arg must have correct number of `X` chars.
With current version, `install.sh` on Linux was failing with error `mktemp: too few X's in template`
Removing `-t` to use defaults on both, Linux and macOS

Use mktemp without any argument

---

internal/build/binary/binary.go
internal/build/binary/merge.go
internal/hotreload/constants.go
internal/hotreload/hotreloadmodule.go
internal/languages/nodejs/opaqueintegration/opaquenodejs.go
internal/languages/opaque/opaque.go
internal/languages/types.go
internal/languages/web/web.go
internal/parsing/integration/nodejs/nodejs.go
internal/runtime/kubernetes/deployment.go
internal/testdata/integrations/dockerfile/simple/README.md
internal/testdata/integrations/dockerfile/simple/server.cue

Syntax:
```
mounts: "/app/src": {
syncWorkspace: fromDir: "src"
}
```
Implementation:
If there is a "syncWorkspace" mount:
- A layer with the "filesync-controller" is added to the built image.
- `ns dev` uses a custom "hot reload" module that forwards filesync events to the dev observer (same way it works for node.js/web today).
- The dev observer starts the filesync controller process inside the same container. When `ns dev` exists, it sends `Ctrl-C` to the controller process. As a failsafe, ns kills all controller processes before starting one.
The existing Node.js/Web filesync works the same way as before and not migrated to the new way in this PR.

Implementing filesync for opaque dockerfiles.

---

internal/filewatcher/filewatcher_darwin.go

following the fsnotify/fsevents recommendation, we should resolve potential symlinks with`filepath.EvalSymlinks` to get the target path to watch.

resolve potential symlinks before initialize fsevents.EventStream

---

internal/wscontents/wscontents.go

It prevents calling `checkChanges` on file paths that are invalid relative paths. For example, if the NS workspace is on $HOME and changes are made with vim, the `checkChanges` are called with ../.viminfo relative path which is an invalid path for the `fs.FS.Open` and it returns EINVAL that causes a fatal internal error. This is an attempt to fix these cases.

internal/wscontents: ignore changes to files which are not valid paths for example includes '..'

---

internal/cli/cmd/prepare/cmd.go
internal/frontend/cuefrontend/module.go
std/pkggraph/workspacedata.go

The implementation supports environment purpose, runtime, and labels:
For example:
```
ns prepare local --env=foobar --create-env \
--create-env-args='purpose=development,runtime=kubernetes,"labels=a=b,c=d"'
```

implements ability to create new environment with prepare

---

framework/kubernetes/kubeparser/from_reader.go

I'm experimenting with complex Kubernetes manifests like the cert manager. It uses these Kubernetes kind that is missing from the `messageTypeFromKind` function.

add MutatingWebhookConfiguration type

---

.github/workflows/e2e.yaml
internal/fnapi/tenants.go
internal/prepare/nscloud.go
internal/providers/nscloud/api/rpc.go
internal/providers/nscloud/api/types.go
internal/providers/nscloud/registry.go

internal/providers/nscloud: use tenant tokens for image registry authN

---

internal/auth/auth.go
internal/auth/tokens.go
internal/auth/userauth.go
internal/build/buildkit/client.go
internal/cli/cmd/auth/login.go
internal/fnapi/tenants.go
internal/providers/nscloud/api/dial.go
internal/providers/nscloud/api/rpc.go
internal/providers/nscloud/registry.go

Also in this change:
- In admin mode we exchange user token to a tenant token with an admin scope.
- Changed registry to use the cached tenant token without exchanged to a scoped token.

internal/auth: cache tenant token on login

---

internal/cli/cmd/cluster/cmd.go
internal/providers/nscloud/api/rpc.go
internal/providers/nscloud/api/types.go

nsc/log: use include instead of a selector in logs request

---

std/networking/gateway/controller/transcodersnapshot.go

This ought to save a lot when transferring large JSONs.
See [NSL-624](https://linear.app/namespacelabs/issue/NSL-624/cloudnamespacesoclusters-is-slow-for-users-is-has-a-large-cluster).

Enable gzip compression in Envoy. Unconditionally.

---

internal/auth/tokens.go
internal/auth/userauth.go
internal/cli/cmd/auth/login.go

I often run into the inconvenience when I run `ns login` by mistake. And it immediately resets the login state, so I cannot just cancel the login process and keep the old auth.

internal/auth: Avoid resetting login state before new login succeeds.

---

internal/auth/tokens.go

internal/auth: support workload tokens to be used instead of tenant

---

cmd/nsc/main.go
install/install_nsc.sh
internal/cli/cmd/cluster/docker.go

Tested:
```
{
"auths": {
"ghcr.io": {},
"https://index.docker.io/v1/": {}
},
"credsStore": "desktop",
"credHelpers": {
"nscr.io": "nsc"
}
}
```
```
docker pull nscr.io/<workspace-id>/ns-go-app:v0.0.1
```

nsc/cred-helper: docker-login installs docker-credential-nsc helper

---

internal/cli/cmd/cluster/attachdocker.go
internal/cli/cmd/cluster/build.go
internal/cli/cmd/cluster/buildx.go
internal/providers/nscloud/api/rpc.go
std/networking/gateway/controller/transcodersnapshot.go

* State file to stable location
* Add node group name to metadata.json, so cleanup command can read it and avoid asking user for `--name` input
* Add background process ID to metadata.json, so cleanup command can read it and seng SIGTERM signal
* Implement SIGTERM handler to buildx proxy
* Print informative message even when buildx proxy is run in background
* Delete state folder when cleanup command is called
* Print error message if state metadata.json file is found
Fixes: NSL-1137

cluster/buildx: cleanup background proxy with state management

---

internal/cli/cmd/cluster/expose.go
internal/providers/nscloud/api/types.go

Example usage:
```
% nsc create --bare                             
Created new ephemeral environment! ID: h2l7pd2jl28c4
% nsc run --image nginx -p 80 --on h2l7pd2jl28c4 --name=my-nginx                               
Started "my-nginx"
Exported 80/tcp as https://6q1i8ko-h2l7pd2jl28c4.fra1.nscluster.cloud/
% nsc expose h2l7pd2jl28c4 --container=my-nginx --container_port=80 --name=myingress
Exported port 80 from my-nginx (74d8e89c2b436cb1ba3b1cff24552b451899c8408bd7f5712b15bdb2):
https://myingress-h2l7pd2jl28c4.fra1.nscluster.cloud/
```

nsc expose: Allow naming ingresses

---

internal/cli/cmd/cluster/docker.go

`docker-credential-helpers` client writes to helper stdin without `\n` termination, so we simply read the whole input.
See: https://github.com/docker/docker-credential-helpers/blob/master/client/client.go#L54
NSL-2086

docker-credential-nsc: read from stdin with bufio.Scanner

---

internal/providers/vault/certificate.go
internal/versions/versions.json

If `common_name` is defined as `svc/foo`, then certificate CN would be `example.com/svc/foo`.

providers/vault: use URI like CN if base_domain is provided

---

std/go/grpc/servercore/mtls.go

std/go/grpc: add an option to provide CA cert via ENV var

---

std/grpc/wire.go

This is a no-op change but the idea is to have a single function provide the loopback client.

grpc: specify loopback address in one place only

---

internal/cli/fncobra/main.go
internal/cli/nsboot/update.go
internal/cli/version/version.go
internal/versions/versions.go

`exec` into the latest version of `nsc` if there is one in the local cache.
Will not `exec` if using a development version (i.e. one **not** built by `goreleaser`).

nsc: exec the latest version if available

---

internal/cli/cmd/cluster/git.go
internal/cli/cmd/cluster/gitcheckout.go

cmd/gitcheckout: resolve submodule relative URL into absolute one from remote origin

---

go.mod
go.sum

v1.2.6 requires distribution@beta1, but internal registry is not compatible with it.
v1.2.4 requires older docker@24, but buildkit requires @27.

Try to satisfy all deps with oras.land/oras-go@v1.2.5.

---

cmd/docker-credential-nsc/binary.cue

cmd/docker-credential-nsc/binary.cue: Add an ns binary definition.

---

internal/cli/cmd/cluster/bazelcredhelper.go

bazel: Fix review comments

---

internal/cli/cmd/cluster/gitcheckout.go

Workers should only exit when the full process is done (doneSignal) or
when canceled.
They should not exit when a single work item finished without error.

gitcheckout: Fix workers exiting when a work item is done

---

std/monitoring/tracing/wire.go

tracing: add http.request.header.referer

---

internal/auth/tokens.go
internal/cli/cmd/auth/login.go
internal/cli/cmd/cluster/buildx.go
internal/cli/cmd/cluster/server_side_buildx.go
internal/fnapi/fnapi.go
internal/fnapi/signin.go
internal/fnapi/tenants.go
internal/fnapi/tokens.go

If not running on a ns instance and a session token is available, use a session client cert for auth to the buildx proxy.
Also refresh it if it existed and then nsc login was performed.

Use session client cert for buildx outside of ns instances

---

std/go/grpc/extension.cue

This is necessary to support some clients with the go-grpc 1.67+ uprev.
See also NSL-4866 and NSL-4857.

Set GRPC_ENFORCE_ALPN_ENABLED false for go-grpc servers

---

internal/build/buildkit/base.go
internal/build/buildkit/computable.go
internal/environment/ci.go

This is a quick workaround for https://linear.app/namespacelabs/issue/NSL-4847/ns-build-binary-consumes-all-memory

Don't digest local inputs in buildkit builds by default

---

internal/networking/ingress/nginx/ingress.yaml
internal/networking/ingress/nginx/ingress_webhook.yaml

Fixes CVE-2025-1974
Based on helm release -
https://github.com/kubernetes/ingress-nginx/releases/tag/helm-chart-4.12.1

ingress/nginx: upgrade to 1.12.1

---

internal/build/buildkit/client.go
internal/cli/cmd/cluster/buildproxy.go
internal/cli/cmd/cluster/buildx.go
internal/cli/cmd/cluster/server_side_buildx.go

Adds a connectivity check to `nsc docker buildx status` that actually prints helpful messages.
The same connectivity check is performed when using remote builders in ns build(-binary).
While we're here, perform some clean up.

buildx: Support connectivity test

---

internal/cli/cmd/cluster/server_side_buildx.go

This fixes a regression introduced in 81c88bf5821607176a17477cc106a695dcd18eae

buildx: Fix wrong platform specifier

---

internal/cli/cmd/gcp/federation.go

This fixes support for identity providers in the formats:
- `https://iam.googleapis.com/projects/<PROJECT_NUMBER>/locations/global/workloadIdentityPools/<POOL_ID>/providers/<PROVIDER_ID>`
- `/projects/<PROJECT_NUMBER>/locations/global/workloadIdentityPools/<POOL_ID>/providers/<PROVIDER_ID>`

nsc/gcp: trim leading slashes from gcp identity provider input

---

internal/cli/cmd/auth/oidc.go
internal/cli/cmd/aws/ecr.go
internal/cli/cmd/aws/federation.go
internal/cli/cmd/aws/setupwebidentity.go
internal/cli/cmd/gcp/federation.go
internal/fnapi/tenants.go
universe/vault/credentials.go

- Add --duration flag to change the namespace token validity duration
- Add --gcp_token_lifetime flag to change configured gcp token duration
- Use existing duration flag for token in aws, ecr, oidc federation cmds

nsc/gcp: allow configuring token duration for nsc gcp impersonate

---

internal/cli/cmd/cluster/build.go
internal/cli/cmd/cluster/github/build.go

- **gihub: remove unused definition.**
- **github: pass an empty-ish context so the build doesn't complain about a non existing dockerignore.**

descriptions

---

internal/cli/cmd/cluster/build.go

cluster/build: Skip adding NSCR prefix if user already specified it

---

internal/cli/cmd/cluster/build.go
internal/cli/cmd/cluster/github/build.go

builds: flag to use server-side mtls proxy for nsc build command

---

internal/cli/cmd/cluster/build.go

builds: default to use server-side mtls proxy for nsc build command

---

internal/cli/cmd/cluster/server_side_buildx.go

builds: ensure that parent dir exists, if not create it

---

internal/cli/cmd/cluster/run.go

nsc: un-hide --enable_docker flag for nsc run
